[project]
name = "coding-agent-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Samuel H.Mariam", email = "samhmariam@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "openai>=3.19.2",
    "python-dotenv>=1.2.3",
]

[project.scripts]
coding-agent-from-scratch = "coding_agent_from_scratch:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
